version: '2.8'

services:
  postgres-container:
    image: postgres:15.15-trixie
    container_name: postgres-container
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 30s
      retries: 5

  data-ingestion-continer-py:
    build: data_ingestion_python/.
    container_name: data-ingestion-container-py
    depends_on:
      postgres-container:
        condition: service_healthy

  data-ingestion-container-dlt:
    build: data_ingestion_dlt/.
    container_name: data-ingestion-container-dlt
    depends_on:
      postgres-container:
        condition: service_healthy
    # This overrides the 'localhost' value from .env file as postgres is hosted in belwo container.
    environment:
      - DESTINATION__POSTGRES__CREDENTIALS__HOST=postgres-container
    